export const data: any =[
    {
        "DepartureStation": "BGA",
        "ArrivalStation": "BTA",
        "FlightCarrier": "AV",
        "FlightNumber": "8020",
        "Price": 1000.0,
    },
    {
        "DepartureStation": "BTA",
        "ArrivalStation": "CTG",
        "FlightCarrier": "AV",
        "FlightNumber": "8030",
        "Price": 2000.0,
    },
	{
        "DepartureStation": "CAL",
        "ArrivalStation": "MED",
        "FlightCarrier": "AV",
        "FlightNumber": "8040",
        "Price": 1500.0,
    },
	{
        "DepartureStation": "MED",
        "ArrivalStation": "STA",
        "FlightCarrier": "AV",
        "FlightNumber": "8050",
        "Price": 4000.0,
    },
	{
        "DepartureStation": "BGA",
        "ArrivalStation": "MED",
        "FlightCarrier": "AV",
        "FlightNumber": "8060",
        "Price": 1000.0,
    },
	{
        "DepartureStation": "MED",
        "ArrivalStation": "CTG",
        "FlightCarrier": "AV",
        "FlightNumber": "8070",
        "Price": 1000.0,
    },
	{
        "DepartureStation": "CAL",
        "ArrivalStation": "CTG",
        "FlightCarrier": "AV",
        "FlightNumber": "8080",
        "Price": 1000.0,
    },
	{
        "DepartureStation": "BTA",
        "ArrivalStation": "MED",
        "FlightCarrier": "AV",
        "FlightNumber": "8090",
        "Price": 1000.0,
    },
	{
        "DepartureStation": "MED",
        "ArrivalStation": "CAL",
        "FlightCarrier": "AV",
        "FlightNumber": "9000",
        "Price": 1000.0,
    },
	{
        "DepartureStation": "CAL",
        "ArrivalStation": "BGA",
        "FlightCarrier": "AV",
        "FlightNumber": "9010",
        "Price": 800.0,
    },
	{
        "DepartureStation": "BTA",
        "ArrivalStation": "BGA",
        "FlightCarrier": "AV",
        "FlightNumber": "9020",
        "Price": 1200.0,
    },
	{
        "DepartureStation": "BTA",
        "ArrivalStation": "CAL",
        "FlightCarrier": "AV",
        "FlightNumber": "9030",
        "Price": 600.0,
    },
	{
        "DepartureStation": "CAL",
        "ArrivalStation": "BUG",
        "FlightCarrier": "AV",
        "FlightNumber": "9040",
        "Price": 800.0,
    },
	{
        "DepartureStation": "STA",
        "ArrivalStation": "BTA",
        "FlightCarrier": "AV",
        "FlightNumber": "9050",
        "Price": 1000.0,
    },
	{
        "DepartureStation": "STA",
        "ArrivalStation": "BGA",
        "FlightCarrier": "AV",
        "FlightNumber": "9060",
        "Price": 1200.0,
    },
		{
        "DepartureStation": "BTA",
        "ArrivalStation": "CUC",
        "FlightCarrier": "AV",
        "FlightNumber": "9070",
        "Price": 1200.0,
    },
	{
        "DepartureStation": "CUC",
        "ArrivalStation": "STA",
        "FlightCarrier": "AV",
        "FlightNumber": "9080",
        "Price": 1200.0,
    },
]